### PR TITLE
Remove all contact related elements; edits to contact model

### LINKED ISSUE #127: Move Contacts item info back to employer item fields
Rework the backend code to adjust for this change
Fix employer home page to adjust for this change

### PR DESCRIPTION
**Pull request by jordanjanakievski**
# Description

Removes contact from being used in the database
Removes the endpoints for contact
The Contact model is edited to work within Employer

Fixes #127 

## Sample curl
curl --location 'http://localhost:3001/api/employer' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "Test",
"primary_address_id": "641a3f2f6a375b37c69d31df",
"creator_id": "63bb1f16939f28affbacf5fc",
"owner_id": "63bb1f16939f28affbacf5fa",
"timeline": "",
"contact_info": {
    "phone_num": "111111111",
    "email": "email@email.com",
    "alt_phone_num": null,
    "website": null
},
"legal_name": null,
"hr_contacts": null,
"secondary_address_id": "641a3f456a375b37c69d31e0",
"initial_contact": null
}'
## Response
Successfully created a new employer with id 641ccfc46fd3874c1cccd288

## Type of change

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
EmployerHome has been updated accordingly to address this change
- [X] This change requires a documentation update
Update has already been reflected in the Wiki

# Checklist:

- [X] I have run `npm run lint:fix`
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by jordanjanakievski** [comment]
Currently facing a Mongo Document failed validation error. Once this is solved, should be good to go

**Review by kenneth-miura — APPROVED** [review]
lgtm!

**Review by ganeshasapu — APPROVED** [review]
everything lgtm!

**Review by helen-li — APPROVED** [review]
Skimmed through quickly but looks slay!

**Pull request merged**
