### PR TITLE
Navigation Bar, MUI

### PR DESCRIPTION
**Pull request by Manal-jpg**
Added simple responsive navigation bar on top
Screen Shot 2022-11-13 at 14 51 58
Screen Shot 2022-11-13 at 14 52 48

### CODE REVIEW

**Comment by kenneth-miura** [comment]
can u open this to dev instead of main

**Review by jordanjanakievski — APPROVED** [review]
Ran everything in docker and the UI is looking good. Responsiveness worked as well.

**Review by helen-li — APPROVED** [review]
Everything works & good use of components and hooks!

**Review by jordanjanakievski — APPROVED** [review]

**Comment by kenneth-miura** [comment]
sorry for miscommunication, this is a practice thing

**Pull request closed without merging**
