### PR TITLE
Add files/folders for job posts and job applications CRUD

### PR DESCRIPTION
**Pull request by 04kash**
# Description
Add files/folders for job posts and job applications CRUD

### CODE REVIEW

**Review by miekoyao — DISMISSED** [review]
The new files look good! Did you add the folders too? Github doesn't seem to display them

**Comment by 04kash** [comment]
Oh, might have to add some files to the folder for them to show up

**Review by miekoyao — APPROVED** [review]
looks good! updated 2 of the files to have camel case naming instead of pascal case

**Review by williamntlam — APPROVED** [review]
Looks good!

One thing was the lack of functionality for deleting a job application. I'm not sure if this is needed or not, but I just wanted to take note of it just in case. If it's not needed then please feel free to ignore what I said above!

William

**Pull request merged**
