### PR TITLE
Setup & Dockerize MongoDB

### PR DESCRIPTION
**Pull request by helen-li**
My 1st time with a local mongoDB instance so please make sure my setup is what was originally intended by #2 
Also took a stab at #7 since I was already setting up the database - seems like it's acting properly but I need sanity check lol

Screenshots: 
* Running server locally: Screen Shot 2022-10-30 at 7 25 37 PM
* Running in Docker containers: Screen Shot 2022-10-30 at 7 25 57 PM Screen Shot 2022-10-30 at 7 26 29 PM

Some resources that saved my last 2 brain cells:
* Followed [this guide](https://www.mongodb.com/docs/drivers/node/current/fundamentals/connection/connect/#std-label-node-connect-to-mongodb), specifically instructions under the "Connect to a MongoDB Server on Your Local Machine" section
* Pretty helpful [MongoDB setup guide](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/) for anyone interested/wants help with getting started

### CODE REVIEW

**Comment by edwardhuahan** [comment]
Looks good! Sorry the github actions keeps failing for some reason I'm gonna disable it temporarily

**Comment by helen-li** [comment]
> Do we need to manage secrets with this? Or does a local MongoDB instance not require this?
> 
> Also make sure to add two people as reviewers that's not me or kenneth and explain to them how it works if they have trouble understanding

I think we can add access control / auth, if that's what you mean by secrets? Just wasn't sure whether I should be setting that up as well

I was waiting on the dev branch to be made before requesting reviews? Looking back that was kinda unnecessary lol will request now

**Comment by edwardhuahan** [comment]
Whoops yeah mb I'll try and set one up once we finish project setup and work on features. By secrets I was wondering if there were like hidden API keys that we shouldn't be exposing but I'm realizing it's local so we should be good

**Review by jordanjanakievski — APPROVED** [review]
Looks good. And everything is running properly on my end as well.

**Review by ganeshasapu — APPROVED** [review]
Everything is working well on my end!

**Comment by annie951977** [comment]
image

I can't actually seem to run this for some reason so I'm just curious to know if there's something wrong, set up wise on my side

**Comment by helen-li** [comment]
> image
> 
> I can't actually seem to run this for some reason so I'm just curious to know if there's something wrong, set up wise on my side

Hello hello! I think the issue might be that mongoDB is not running on your mac yet - you can check whether it's running with the command `brew services list` (You should see the service `mongodb-community` listed as `started`). To start mongoDB, you can run `brew services start mongodb-community@6.0`. More details are in [this setup guide](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/). Let me know if that still doesn't solve the issue!

**Pull request merged**
