### PR TITLE
[TCES-56][MERGED]: Create Custom Job Type Chips

### PR DESCRIPTION
**Pull request by williamntlam**
# Description

This pull request is for the implementation of the job type chips component. 

image

Linear.app Link: https://linear.app/tces/issue/TCES-56/create-custom-job-type-chips

Issue #TCES-56

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Checklist

Please delete options that are not applicable.

- [X] My code follows the style guidelines of this project (required)
- [X] I have performed a self-review of my code (required)
- [X] I have linted and formatted my code (required)
- [X] New and existing unit tests pass locally with my changes (required)

### CODE REVIEW

**Comment by williamntlam** [comment]
Hi! I'm using CodeSandBox.io to test the component and it looks like this:

image

Let me know if there is anything you would like me to change.

The component features a Box component within another Box component from the MUI library. Please let me know if something else was wanted in terms of the implementation.

Thanks,

William.

**Comment by williamntlam** [comment]
I updated the component to better match the given image.


Hope that helps!

William.

**Comment by miekoyao** [comment]
This looks great so far William, thank you for your work! I just updated the linear ticket with an image with hex codes for the various colours (including the border colours) for each of the bubbles. 

Would it also be possible to use the Roboto font to match the MUI components we are using? Thank you! 

Let me know if you need anything else!

**Comment by williamntlam** [comment]
Hi! I updated the code to better match the Job Type Chips image that was uploaded onto the linear.app issue.

image

Hope that's okay,

William.

**Review by 04kash — COMMENTED** [review]
Can you change the file path to client/src/components/view-job-posts-component/job-type-chips-component/index.jsx ?

**Review by 04kash — APPROVED** [review]
Lgtm!

**Pull request merged**
