### PR TITLE
TCES-70 Add pages hotfix option to remove multiple of the same

### PR DESCRIPTION
**Pull request by 3milyfz**
# Description

Added option to remove when there are multiples of the same object for:

**ADD EMPLOYER**
- Secondary address
- Employer contacts
- Job lead cards

**ADD JOB LEAD**
- Job lead cards

**ADD CLIENT**
- Client cards

https://github.com/uoftblueprint/tces/assets/73791848/d7e37c70-f687-451a-bfb9-d14822c3395a

Completed TCES-70

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist

Please delete options that are not applicable.

- [X] My code follows the style guidelines of this project (required)
- [X] I have performed a self-review of my code (required)
- [X] I have linted and formatted my code (required)
- [X] New and existing unit tests pass locally with my changes (required)
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by jordanjanakievski — COMMENTED** [review]
Looking and functioning great. The connection to the backend is working as expecting. Only one minor functional comment. When deleting an item, it is not necessarily deleting the one that I clicked, just deleted the most recent or in these cases, the one at the bottom.

For example, I have three clients: 1, 2, 3

I click to delete client 2 but the remaing clients are 1 and 2. So we lost 3.

Thats my only note, otherwise everything is looking good

**Comment by jordanjanakievski** [comment]
Just a separate note, lets remove the required from client phone number and email since there are some cases where that data will not be available for the tces employee

**Review by jordanjanakievski — COMMENTED** [review]
The Client and Job Lead are working as expected. The add employer is crashing in the add job section. When I go to add a new job, it crashes by routing back to the employer dashboard.

**Comment by jordanjanakievski** [comment]
Crashing in the add employer workflow has been handled in #77 
Once merged should fix this blocker

**Review by jordanjanakievski — APPROVED** [review]
After merging in the changes from #77 all features are working as expected

**Review by kevinle623 — APPROVED** [review]

**Pull request merged**
