### PR TITLE
Small bug fixes

### PR DESCRIPTION
**Pull request by kevinle623**
# Description

Fixed the following bugs:
1. You can’t set a client to have a closed status with status at exit being employed (not sure if its exclusive to the employed status at exit). [FIXED]
2. When you set the value of fields such as NOC code, hours per week and # of positions to 0 they show up as not filled out in the front end. For example try setting a job lead’s noc code to 0 and then on the job lead page it will say Edit NOC Code… I presume this is due to checking for the existence of these values — ex: if (NOC_code) ... . When NOC_code is 0 this check will fail, even though NOC_Code is present. [FIXED]
3. compensation range filter on job leads table is broken: try the range 0 - 30, the first result doesn’t fit in that range [FIXED]
4. New thing that I noticed, number of positions can be reduced below the number of people currently assigned to a job. This leads to situations where we have a person assigned to a job while having 0 positions for that job. [FIXED]
5. Also another small bug I just noticed: I don’t think the Hours/Week Filter is working as intended [FIXED]
 
Issue # N/A

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist

Please delete options that are not applicable.

- [x] My code follows the style guidelines of this project (required)
- [x] I have performed a self-review of my code (required)
- [x] I have linted and formatted my code (required)
- [x] New and existing unit tests pass locally with my changes (required)

### CODE REVIEW

**Review by jordanjanakievski — DISMISSED** [review]
Code looks good to me and the changes are working as expected. Thank you!

**Review by DanielDervishi — DISMISSED** [review]
Great work Kevin!

**Review by DanielDervishi — APPROVED** [review]
Awesome! Thanks Kevin!

**Review by jordanjanakievski — APPROVED** [review]
Looks great. Thank you!

**Pull request merged**
